import type {Metadata} from 'next';
import './globals.css';
import Footer from '@/components/Footer';
import ClientSideMenu from '@/components/ClientSideMenu';

export const metadata: Metadata = {
  title: 'Martin\'s Portfolio',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientSideMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}


